import Head from "next/head";
import MyPersonalPhoto from "components/atoms/my-personal-photo";
import Link from "next/link";
import ProjectTimeline from "components/organisms/project-timeline/ProjectTimeline";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nerea Pardo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-stone-900 flex flex-col items-center pt-16 text-white">
        <MyPersonalPhoto />
        <h1 className="my-6 text-5xl">
          Hi, I am <span className="font-bold">Nerea Pardo Cundíns</span>
        </h1>
        <h2 className="font-light text-4xl">Nice to meet you!</h2>
        <div className="mx-8 mb-24">
          <p className="font-light my-8 text-stone-400 text-2xl mb-14">
            I am a Full-Stack web developer and my motivation is to help people
            through quality software that can make their lives easier.
          </p>
          <div className="flex justify-around">
            <Link href="/aboutme">
              <a className="rounded-3xl border-2 border-neon py-1 px-4 font-light text-neon text-2xl">
                More about me &#10141;
              </a>
            </Link>
            <Link href="https://drive.google.com/file/d/1QHBUhQEKw-sKHnl4cO-3Dvtuc-plKL7-/view?usp=sharing">
              <a
                className="rounded-3xl bg-neon py-1 px-4 text-2xl text-slate-900 font-bold"
                target="_blank"
              >
                My resume
              </a>
            </Link>
          </div>
        </div>

        <h2 className="text-5xl mb-6">My projects</h2>
        <ProjectTimeline />
      </div>
    </>
  );
}
