import Head from "next/head";
import MyPersonalPhoto from "../components/atoms/MyPersonalPhoto";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nerea Pardo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-stone-900 flex flex-col items-center pt-12 text-white">
        <MyPersonalPhoto />
        <h1 className="mt-6 font-light">
          Hi, I am <span className="font-medium">Nerea Pardo Cundíns</span>
        </h1>
        <h2 className="font-light">Nice to meet you!</h2>
      </div>
    </>
  );
}
